# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6de0c55a89d99a5d42b4fadc8afeec27419122257e366aee73adacdd2284c86de6227d7f7c0438ad0721d1fc9216c7eed9a2f097705831a186366f50df2d4c74

test:
  secret_key_base: 7c66506721a07e299b1312066324b78482d601210aa07cc44bc15bb63e43cd053a4417c3dd97c3ad4f4186b2497ce782522b9f5d0cf26afe961c306b45db9443

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
